---
- name: latest mariadb version installed
  yum:
    name: "{{ packages }}"
    state: latest
  become: yes
  vars:
    packages:
      - mariadb
      - mariadb-server
  notify:
    - conf_innodb_strict_mode
    - conf_character_server
    - conf_character_client
    - restart_mariadb
