---
- name: latest mariadb version installed
  yum:
    name: "{{ packages }}"
    state: latest
  become: yes
  vars:
    packages:
      - mariadb
      - mariadb-server
  notify:
    - restart_mariadb
